### ISSUE TITLE
Publish Position Paper

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#247]
## Summary

Publish position paper 

## Date Due by

Summer 2022

## Tasks

This paper needs updating following project progress

- [x] recruit co-author
- [x] write initial draft
- [x] circulate 
- [x] make revisions
- [x] gather wider feedback
- [ ] write updated draft 
- [ ] make more revisions
- [ ] recruit further co-authors
- [ ] gather feedback
- [ ] create final draft
- [ ] select appropriate open journal
- [ ] send for publishing
- [ ] link to paper from repo
