### ISSUE TITLE
Create moderation summaries 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#416]
## Summary

Create pseudonymised summaries of moderation discussion from December session. These will be used to support writing the code of conduct, designing the platform's moderation process, and writing research papers. 

## Tasks needed for completion 

* [x] Create full transcripts of session
* [x] Pseudonymise, label, and break up into quotes 
* [x] Send round participants individually to make sure they approve it, (along with guidance document co-written with James)
* [x] Do quali analysis by pulling out themes, and structuring quotes (involve Susanna in this process)
* [x] Put these into an md file and upload to repo 

## Who can help

Only Georgia can do the fiirst 3 tasks due to privacy/data management sensitivities. The other tasks will be a collaboration between @JamesSCTJ, Susanna, and Georgia. 

Comment on this issue if you want to help out.

**Comment by GeorgiaHCA** [comment]
This is the next major research task for the project so pinning it.

**Comment by lottycoupat** [comment]
@GeorgiaHCA Is there an issue to be raised on this for picking out themes from the moderation summaries? I think you highlighted this task in our meeting?

**Comment by GeorgiaHCA** [comment]
Heya Lotty! Yes, so this is the work that needs to be fed into the moderation planning, as it is all the rich community discussion. Maybe worth linking this issue to the moderation as it is dependancy

**Comment by skfantoni** [comment]
@GeorgiaHCA @lottycoupat I started going through the previous focus group summaries yesterday and am already picking up on themes. With Moderation Process, Flagging and Tagging being the ones I've noticed so far. Is this what you mean?

**Comment by GeorgiaHCA** [comment]
@skfantoni - exactly! So these are from a whole wide range of people, including autistic people from different backgrounds, ethnicities, genders, different age ranges - so genuinely thinking about these, incorporating them in some way, or acknolwedging when differences mean having to make choices, or values misalign, or compromises have to be made for feasibility, is how we can make sure that the moderation process is co-created with the community

**Comment by GeorgiaHCA** [comment]
Balancing it is super tricky, it's really impressive work you're doing thank you so much!

**Comment by GeorgiaHCA** [comment]
Hiya! I'm just about there with the summaries notes, but I wanted to ask a few questions @JamesSCTJ, @skfantoni, @lottycoupat, @KirstieJane - any thoughts on any of these things super appreciated.

**Comment by GeorgiaHCA** [comment]
1. I recognis the importance of recognising intersectionality, gender, co-occuring conditions, and other fine-grained details which could effect the intrepretation and underestanding of the research. I know we've discussed this recently @skfantoni. I think in this instance, the number is people participating is small, and so it is quite likely that individuals could be identified easily if we used these more fine-grained profiles. Since we did not say that we would offer it, the options would be 
1. to get in touch with people and probably only apply additional labels if everyone in the group was happy that it would reduce the anonymity of the comments
2. to leave the comments as is without additional labels 
3. to include intersectional aspects as part of the 'direct' and 'indrect' labelling system

**Comment by GeorgiaHCA** [comment]
Second q: for sending out the summaries, my thinking is that it would make sense to: 1) send out the pieces of conversation (unintegrated into the summary) that happened for each private group first, to give those peeople the chance to edit out what they didn't want to share with the whole group. 2) edit those where they are in the larger summary - my concern is that there is a possibility that even after that process, the content of the discussion is sensitivie. I think we would certainly need to providde an explanation of this before publishing, and maybe before sending out too. What are yor thoughts?

**Comment by GeorgiaHCA** [comment]
Final q: we need guides to go along with the summaries. I loved the ones you did for the previous focus groups @JamesSCTJ - would you be able to adapt them for this? (If so, I'll make an issue).

**Comment by GeorgiaHCA** [comment]
Really amazing stuff, everyone! I'm thrilled by your dedication and also reading through the conversations again I was struck by just how considerate, thoughtful, nuanced and empathic everyone was. I have a few things I need to give my attention to first as urgent priorities, but can't wait to pick this up again. Very excited for the next phase.

**Comment by GeorgiaHCA** [comment]
Moderation summaries combined and uploaded, including requested changes made. Stlil needs extra proof reading.
