### ISSUE TITLE
Prepare for next meet-up session

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#431]
## Summary

The next AutSPACEs meet-up session will be held soon. We need to prepare an agenda, and make sure we communicate it. 

## Date Due by

Session is on Thursday 11th March 12-30-2:30pm

## Tasks to be done

* [x] Agenda decided
* [x] Participants reminded/notified
* [x] Working doc to be created 
* [x] Faciliatators arranged
* [x] Any adjustments needed put in place

## Who can help

Anyone can make suggestions; offer to facilitate

**Comment by GeorgiaHCA** [comment]
# AutSPACEs Online Meet-ups 2021

**You are invited!** Take part in our online meet-ups.  

We are hosting online meet-up sessions for the Autistica/Turing Citizen Science project. You are invited! The sessions will take place every **2nd** and **4th** Thursday of the month on Zoom. The details for the next session are:

  **Day:** Thursday 11th March
**Time:** 12:30pm - 2:30pm (GMT)
**Location:** ZOOM https://turing-uk.zoom.us/my/georgiahca
**Agenda:**

| Time | Activity |
| ---- | -------- |
| Start | 👋 Welcome, code of conduct review |
| 12:40pm  | Introductions |
| 12:45pm  | Working groups and pathways to involvement |
| 1pm  | Personal goal setting, subgroup selecting, and Q&A |
| 1:20pm| ☕️ Break |
|1:40pm | Subgroup discussions and co-working |
| 2:20pm | Open discussion and plans |
| 2:30pm | 👋 Close |

(those who are already familiar with the project and want to go straight to a subgroup can do so - breakout rooms will be opened after the code of conduct review)

**Comment by GeorgiaHCA** [comment]
Heya! I would appreciate advice on the above agenda/invite? Also any volunteer facilitators would be hugely appreciated!

**Comment by GeorgiaHCA** [comment]
Current subgroups identified from previous meet-up sessions are:

- Comms, engagement, and promotion    
- Research    
- Moderation    
- Accessibility and inclusion    
- Platform Development    

(with lots of participants members of multiple groups)

**Comment by BrainonSilicon** [comment]
The agenda itself looks good! I would ad "go into breakout rooms" and "return to main room for discussion" so that if someone comes in halfway through they'll know where we are.

**Comment by GeorgiaHCA** [comment]
Thanks @BrainonSilicon - good idea

**Comment by GeorgiaHCA** [comment]
Fab meet-up session everyone! Closing this and opening a new issue for the next one.
