### ISSUE TITLE
Prepare for next AutSPACEs meet-up session

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#433]
## Summary

The next AutSPACEs meet-up session will be held soon. We need to prepare an agenda, and make sure we communicate it. 

## Date Due by

Session is on Thursday 11th March 12-30-2:30pm

## Tasks to be done

* [ ] Agenda decided
* [ ] Participants reminded/notified
* [ ] Working doc to be created 
* [ ] Faciliatators arranged
* [ ]  Any adjustments needed put in place

## Who can help

Anyone can make suggestions; offer to facilitate
It is also really helpful to have feedback if you attended a session or would like to

**Comment by GeorgiaHCA** [comment]
# AutSPACEs Meet-up Session

We are excited to be hosting our third meet-up session
[What is AutSPACEs - who is it for - and what we do in the meetup session] - highlight important words
Who I am (+email)
Links - check out website etc. - Twitter

**When?** Thursday 25 March 2021, 12:30 - 14:30 UTC ([see in your time zone](https://arewemeetingyet.com/London/2021-03-03/15:00))

**Next call:** 8 April 2021, 12:30 - 2:30 UTC ([see in your time zone](https://arewemeetingyet.com/London/2021-03-07/15:00))

**How?** **Join Zoom Meeting**

==<Add Zoom Link>==

> :calendar: You're in the right place even if you're early!

***All questions, comments, and recommendations are welcome!***

## Table of Contents

[TOC]

## What to Expect in the Meet-up Session

* We use Zoom for the meeting. You can test Zoom by following this link: zoom.us/test
* You can **drop in** or **drop out** whenever you like. You do not have to attend the whole session unless you want to. 
* You can leave at any point if you want without giving a reason. 
* You can rejoin again whenever you like.
* You can take part by writing (Zoom chat or google doc), speaking, or both. If you prefer to just type in the shared document, that is okay and there is no pressure to speak. If you prefer to speak and not write, that is okay too and we will provide a scribe to make sure your input is captured and included. 
* If you are not talking, please keep your microphone muted, and if you would to talk, please raise your hand.
* If you prefer to keep your camera and microphone switched off and just listen, that is completely fine.  
* We will keep notes in a shared [Google Doc] - link to doc - ()

## Agenda

| Time (GMT) | Activity |
| ---- | -------- |
| 12:30pm | 👋 Welcome, [code of conduct review](link) |
| 12:35pm | Introductions and goal-setting |
| 12:40pm | Breakout room discussion 1|
| 1pm | ☕️ Break |
| 1:05pm | Breakout room discussion 2 |
| 1:35pm | ☕️ Break  |
| 2pm | All return to main room for group sharing/discussion |
| 2:25pm | Open discussion: celebrations, reflections and future directions |
| 2:30pm | 👋 Close |

### Shared timer for this call

[https://cuckoo.team/autspaces-meetup](https://cuckoo.team/autspaces-meetup)
*This link will allow you to keep track of different session.*

## Breakout Room Groups and Activities: Topic proposals

*If you have an idea for a topic you'd like to discuss or work on during the discussion session (either in the main room or in a breakout room), please add it below and put your name next to it. If you like one of the topics that are already suggested, please add your name next to that one. Teamwork makes the dream work.*

*Topics for breakout / Names*

*
*

### If you choose to stay in the main room

* There will always be a facilitator on hand in the main room to welcome new people and talk to anyone. 
* You can come back here any time if you like and stay as long as you like.
* Please ask any questions, explore the project more, or make any requests for adjustments which would make it easier to take part. 
* You can choose which group to join and you can change your mind at any time.
* A moderator can help you choose a group to join or an activity to take part in based on your skills and interests if you are unsure.
* Join back here for group discussion




------

## Explore Current Activities in AutSPACEs

If you're wondering where to start, check out some of the current activities that people are leading. You are welcome to join them, or propose a new task. 

### Comms, engagement, and promotion

*Suggested activities*  

**Sign up below** 
*Please add your name below if you are or would like to be involved in these activities (completely optional!)*  

### Research

*Suggested activities*

**Sign up below** 
*Please add your name below if you are or would like to be involved in these activities*  

### Moderation

*Suggested activities*

* Identify and plan for risks
* Write code of conduct
* Design moderation process

**Sign up below** 
*Please add your name below if you are or would like to be involved in these activities*  

### Accessibility aand inclusion

*Suggested activities*

* Groups to reach out to
* Ways of supporting people to take part
* Design and testing for platform accessibility 
* Metrics
* Investigate Otterley 

**Sign up below** 
*Please add your name below if you are or would like to be involved in these activities*  

### Platform Development
*The key technical skills for the platform development are: Django web development, GitHub, Python. We can also help you learn these skills if you would like to.*

*Suggested activities*

* Going through and fixing issues
* Reviewing PRs
* Discussing progress
* Learning new skills 


**Sign up below** 
*Please add your name below if you are or would like to be involved in these activities*

**Comment by GeorgiaHCA** [comment]
Done!
