### ISSUE TITLE
Complete Updates on Researchfish 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#459]
## Summary

Complete annual reporting of project on Researchfish for Autistica. 

## Details

This is an important record of progress made in the last year. 

## Tasks

Generic Qs

**- Publications - N/A** 
- [x] Add all conference presentations/webinars etc. 
- [x] for April 2020-present 
- [x] pre April 2020
- [x] **Add engagement activities that are not presentations e.g. workshops, meet-ups, co-working etc.**
- [x] Further funding?
- [x] (double check details with AB)
- [x] Participatory/citizen science/open source research as method outcome
- [x] Add collaborators and pro bono support
	- [x] add amounts for pro bono 
- [x] Further funding clarification (Turing?)
- [x] Add focus groups as dataset output 
Intellectual property licensing (N/A)
- [x] Add Scriberia images as creative products (+anything else?)
- [x] Software - add AutSPACEs repository 
- [x] Spin outs - N/A
- [x] Awards and acknowledgements
- [x] Invitations to conferences where you or a member of your team were individually named as a speaker or keynote speaker. (apply to KW?)
- [x] acknowledgements by community members? 
- [x] Other outputs/future steps (obviously lots of future steps - but seems like an N/A in details?)
**Use of facilities and resources (N/A)**

Specific Qs 

- [x] Add academic meeting and conferences attendances
- [x] Include annual progress review
	- [x] refine
- [x] Include participatory science updates and testimonials
	- [x] refine

Finessing

- [x] Double check/polish everything
- [x] Print out and triple check
- [x] Get someone else to check
- [x] Get feedback from Kirstie
- [x] Make changes
- [ ] Submit

Sharing 

- [x] Create a HackMD to hold version of inputs and add to GitHub as an MD document (once anything personal or sensitive taken out)
- [x] Collect feedback
- [x] Include feeddback
- [ ] Submit

**Comment by GeorgiaHCA** [comment]
Pinning issue as a priority

**Comment by GeorgiaHCA** [comment]
I'm adding my to-do list for researchfish so you can see my task list!

**Comment by GeorgiaHCA** [comment]
Would anyone be willing to help me triple-check this for spelling/style/grammar and so on?

**Comment by GeorgiaHCA** [comment]
Heya @KirstieJane is this issue ready to close?
