### ISSUE TITLE
Prepare for CC summit 

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#535]
## Summary

Out submission AutSPACEs: co-creating an open citizen science platform has been accepted as part of the virtual 2021 CC Global Summit, happening Sept 20-24. We need to prepare a 20minute-30minute session 

## Tasks 

- [x]     Let us know you agree to present by completing the Acceptance Form by Aug 2 
- [ ]     Please hold the event dates Sept 20-24. You'll have your presentation time and date when the schedule goes public on Aug 5.
- [ ]     Follow us on Twitter and share on social - let the world know you are presenting, and be sure to tag @ccglobalsummit. 
- [ ]     Join our Summit Slack channel to meet other presenters and participants.
- [x] Decide on who will present - make sure that the organisers are aware. 
- [x] Find a time to plan out presentation together
- [ ] Create presentation
- [ ] Rehearse! 
- [ ] Deliver 

## Who can help

Anyone with ideas or suggestions please leave your comments below!

**Comment by sowmya9507** [comment]
> @sowmya9507 @lottycoupat @JamesSCTJ - would you all still like to be involved in this summit?

Hey @GeorgiaHCA I would be definitely interested to be involved in this summit and thank you so much for asking 😄 Please let me know how can I help out?

**Comment by GeorgiaHCA** [comment]
Fantastic! We will need to prepare something together showcasing our work: https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/applications/cc-global-summit-2021.md - here is the submission I made for reference.

**Comment by GeorgiaHCA** [comment]
How about we set up a co-working session together to make sure everyone is on the same page?

**Comment by sowmya9507** [comment]
Sure, a co-working session would be helpful to understand each other's views 😄

**Comment by lottycoupat** [comment]
@GeorgiaHCA I would also be super keen!! And yes let's co-work on this 😄

**Comment by skfantoni** [comment]
I’m in too if possible!

**Comment by skfantoni** [comment]
I’m happy to be there as a ‘participant’ if you think that would be beneficial to the presentation.

**Comment by GeorgiaHCA** [comment]
Would you like to present @skfantoni ?

**Comment by JamesSCTJ** [comment]
I'd be happy to be involved in the summit.

James

**Comment by KirstieJane** [comment]
This is so exciting! Congratulations! 

One top tip for when you're creating the presentation is to remember that everyone kinda zones out while they're listening (neurodivergent and neurotypical!!) So each slide should have a "take home point" - you don't need to write it on the slide itself (although you can if it makes sense - the title can often be informative, but that sometimes looks rather clunky) but you should KNOW what the take home message is.

I'll also add my standard advice - how do you want people to FEEL when they're listening to you, and what is your call to action - what do you want them to DO after they've heard about our work ✨

**Comment by GeorgiaHCA** [comment]
Heya @skfantoni @anoura12 @sowmya9507 @JamesSCTJ @lottycoupat ! I've put in a calendar invite for next Monday to plan out the CC-Summit session. We'll need to think about how we divide the time we have and what we want people to take away from the session. My thought was we can use this for some initial planning and co-working, but can also arrange another co-working/follow up session with those who can't make the first.

**Comment by GeorgiaHCA** [comment]
https://hackmd.io/JUawWd8MRlGgL6EVTzCqVQ - we are working on a plan here
https://docs.google.com/presentation/d/15zb4eK9oXWRz7Wt4w57V5-FKfB7Hh5t8R4-aAa47tRI/edit#slide=id.p - link to slides here

**Comment by GeorgiaHCA** [comment]
All done! Well done everyone! :tada: :tada: :tada: I've uploaded the latest version and added a link to the Zenodo slides in the presentations section of community-recommendations. Closing this issue now :D
