### ISSUE TITLE
Publish a roadmap linked to issues and milestones

### ISSUE THREAD

**Issue by GeorgiaHCA** [alan-turing-institute/AutisticaCitizenScience#72]
"As a contributor I want to see an overview of the project so that I can make sure my work fits into the plan as a whole" 

- [ ] Organise existing issues into milestones
- [ ] Write a roadmap in mardown which explains the project to new collaborators
- [ ] Link to milestones and issues from roadmap

**Comment by EllenDevereux** [comment]
Milestone - Reporting and accountability

**Comment by EllenDevereux** [comment]
I am responsible for tidying issues and helping to organise the project board so that the community can see what we're doing and when.

@JamesSCTJ I know you've been working on this already.

**Comment by GeorgiaHCA** [comment]
A roadmap has now been published by Lotty!
